language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql TYPO3=TYPO3_6-2 TRAVIS_INTEGRATION=master TYPO3_INTRODUCTION=master
  - DB=mysql TYPO3=TYPO3_6-1 TRAVIS_INTEGRATION=master TYPO3_INTRODUCTION=TYPO3_6-1
  - DB=mysql TYPO3=TYPO3_6-0 TRAVIS_INTEGRATION=master TYPO3_INTRODUCTION=TYPO3_6-0


before_script:
  - cd ..
  - git clone --single-branch --branch $TRAVIS_INTEGRATION --depth 1 git://github.com/typo3-ci/TYPO3-Travis-Integration.git build-environment
  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core
  - source build-environment/install-helper.sh
  - git clone --single-branch --branch $TYPO3_INTRODUCTION --depth 1 git://git.typo3.org/TYPO3CMS/Distributions/Introduction.git build-environment/Introduction
  - mv core/typo3 .
  - if [[ -d core/t3lib ]]; then mv core/t3lib . ; fi
  - mv build-environment/typo3conf .
  - mkdir fileadmin
  - mkdir uploads
  - mkdir typo3temp
  - git clone --depth 1 git://git.typo3.org/TYPO3CMS/Extensions/phpunit.git typo3conf/ext/phpunit

  - ln -s ../../TYPO3-Extension-rs_lock ./typo3conf/ext/rs_lock
  - if [[ -f TYPO3-Extension-rs_lock/Build/$TYPO3/typo3conf/AdditionalConfiguration.php ]]; then cp TYPO3-Extension-rs_lock/Build/$TYPO3/typo3conf/AdditionalConfiguration.php typo3conf/; fi

  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi

script:
  - typo3/cli_dispatch.phpsh phpunit
