<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-01-10 11:14

$extensionPath = t3lib_extMgm::extPath('rs_pagegenlock');
$extensionClassesPath = t3lib_extMgm::extPath('rs_pagegenlock') . 'Classes/';
return array(
	'tx_rspagegenlock_locking_locker' => $extensionClassesPath . 'Locking/Locker.php',
	'tx_rspagegenlock_locking_lockerinterface' => $extensionClassesPath . 'Locking/LockerInterface.php',
);
?>